feat: create getAppointments function in Hooks
MediaWind/react_kiosk_engine pull request #64
Opened 2024-09-26 09:32 UTC by MaximeMediawind

2024-09-27 12:13 UTC, PPolliotti-MediaWind requested changes

2024-09-27 12:13 UTC, PPolliotti-MediaWind commented on hooks/useAppointment.tsx
> +				Console.error("Error when trying to get appointments: data status " + data.status ?? "undefined", { fileName: "useAppointment", functionName: "getAppointments", lineNumber: 209, });
I'm a bit septical about those lineNumber, they seam to be pointing to the wrong line?

2024-10-01 07:49 UTC, FlorentGhilain commented on hooks/useAppointment.tsx
> +		timeStart.setHours(timeStart.getHours() - 1);
The interval allowed to perform the checkin can be given as a widget parameters (in minutes)

2024-10-01 07:55 UTC, FlorentGhilain commented on hooks/useAppointment.tsx
> +		timeStart.setHours(timeStart.getMinutes() - minBeforeAppointment);
You should use `setMinutes` instead of `setHours`

2024-10-01 08:40 UTC, merged